services:
  localllm-engine:
    container_name: localllm-engine
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.engine
    volumes:
      - model_data:/root/.ollama
    ports:
      - "${ENGINE_PORT:-11434}:11434"
    networks:
      - localllm-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  model_data:

networks:
  localllm-network:
    driver: bridge 